### ISSUE TITLE
בדיקת מטלה 5

### ISSUE THREAD

**Issue by michael-lemberger** [LeveI-Up/KingDavid#1]
ברגע שעוברים סצינה המצלמה לא עוקבת אחרי השחקן
![image](https://user-images.githubusercontent.com/44966756/142183197-bcbd739e-abc3-44f1-b4b0-59138545eb33.png)

**Comment by michael-lemberger** [comment]
בנוסף, מה זה:
 newPos.z = -15;
 לא מתקבל

**Comment by saar95** [comment]
תוקן
